fix(dataset-importer): add support for s3 endpoint urls
Paperspace/gradient-cli pull request #337
Opened 2020-12-07 12:51 UTC by reynld

2020-12-07 14:39 UTC, sanfilip requested changes
Do we need to have a dependency on go-importer and the reference to DATASET_IMPORTER_IMAGE?

2020-12-07 21:40 UTC, sanfilip commented
Discussion from slack:


tom  9:24 AM
I see we’ve added references to go-getter to the gradient-cli.  We normally install the gradient-cli with pip.  Won’t this be an issue for all our current users and docs?

chris  9:26 AM
We were using go-getter command to import datasets, this will be changed when I get up our dataset-importer repo that will use the go-getter library instead of the command we are using now
9:27
Don’t think this will impact how users will install gradient-cli

tom  9:31 AM
Not sure I follow.  It looks like it is referenced in the gradient-cli source code: https://github.com/Paperspace/gradient-cli/commit/91cb0f740e906034e857691213c6dcdf76001ae3#diff-4d48689c77885d2c25cabcd77c9386df6235adae2a53921a4bbbbe1361293850R34

philip  9:39 AM
The dataset importer creates a Gradient job, which create sa container with go-getter installed. go-getter then downloads the URL in the job. Chris is moving it more to the future Gradient Action (based off https://docs.github.com/en/free-pro-team@latest/actions/creating-actions/creating-a-docker-container-action) which won't will used a default entrypoint rather than requiring a command. TLDR; no dependencies are added this is just configuring the Gradient Job

tom  9:43 AM
But gradient-cli is just supposed to wrap our api.  We want to have all functionality of the gradient platform available in our api. I think I see what you are doing, but I would be cautious about embedding lots of logic in the command line client.

philip  9:57 AM
I agree we should have minimal logic in the CLI I think Gradient Actions will clean this up since there will be a unifed backend interface to run these tasks. In general I think the separation of concerns are: SDK strict wrapper of API, CLI provides an experience/interface to users in regards to input parameters and API calls.

tom  11:36 AM
Cool.  I know there is a gray area where we may want to use our tools to template some functionality, and the command line also needs to facilitate developers of course.  Gradient Actions (with some pre-defined actions) is definitely the way to go.

2020-12-07 21:42 UTC, sanfilip approved these changes
Chris and Philip answered my questions in slack.  See thread attached.

2021-08-04 18:14 UTC, bbatha commented
Closing we're dropping support for this dataset importer to build it on workflows.

2021-08-04 18:14 UTC, closed without merging